<?php

/*
|--------------------------------------------------------------------------
| Pass Slip Design Templates — Toggle Capability Manifest
|--------------------------------------------------------------------------
|
| Every Design Template (Classic / Modern / Minimal) shares the SAME
| customisation panel today, even though not every toggle actually does
| anything in every template's markup — e.g. "Result box" is currently
| unused by all three, and "Total Score / Marks box" + "Average box"
| only exist in Classic's markup, not Modern's or Minimal's.
|
| The 'nursery-classic' / 'nursery-modern' / 'nursery-minimal' keys
| further down are the equivalent capability lists for the "Nursery
| Design Template" gallery (a second, independent picker on the same
| page — see the 'capabilities' array below for why theirs starts
| deliberately small).
|
| This file is the single source of truth fixing that:
|
|   - 'toggles'      => every show_* switch the customise panel CAN
|                        render, with its label/icon/group.
|   - 'capabilities' => for each template key, exactly which of those
|                        switches actually affect its markup. Anything
|                        not listed here is a dead switch for that
|                        design and is hidden from its panel.
|
| The lists below were generated by measuring real usage of $cfg['key']
| inside each slip-*.blade.php file (not just where the key is
| declared). If a template's Blade markup changes to add/remove a
| section, update its list here to match — that's the only place
| this needs to change.
|
| NOTE (classic): 'show_total_score', 'show_average' and 'show_rank'
| have been superseded in Classic by the granular Summary Bar toggles
| ('show_sum_total_marks', 'show_sum_average_mark', 'show_sum_average_pct',
| 'show_sum_position', etc.) and are no longer in classic's capability
| list. They're left in the registry only so any already-saved settings
| JSON containing the old keys doesn't error out — they're simply
| ignored by Classic now.
|
*/

return [

    'toggles' => [
        'show_border' => ['label' => 'Decorative border & corners', 'icon' => 'fa-border-all', 'group' => 'Appearance'],
        'show_watermark' => ['label' => 'Watermark (logo / school name)', 'icon' => 'fa-stamp', 'group' => 'Appearance'],

        // ── Whole-section master switches ───────────────────────────
        // Turn an entire boxed section off in one click. Independent of
        // the field-level toggles further down — e.g. show_section_student_info
        // OFF hides the box completely regardless of what its individual
        // show_stu_* switches are set to. Placed early/prominently since
        // this is usually the first decision someone makes.
        'show_section_student_info' => ['label' => 'Student Information (entire section)', 'icon' => 'fa-id-card', 'group' => 'Sections'],
        'show_section_summary' => ['label' => 'Performance Summary strip (entire section)', 'icon' => 'fa-chart-simple', 'group' => 'Sections'],
        'show_section_marks_table' => ['label' => 'Marks Table (entire section)', 'icon' => 'fa-table', 'group' => 'Sections'],

        // ── Student Information — per-field toggles ─────────────────
        'show_stu_name' => ['label' => 'Student Name', 'icon' => 'fa-user', 'group' => 'Student Information Fields'],
        'show_stu_admission' => ['label' => 'Admission No.', 'icon' => 'fa-id-badge', 'group' => 'Student Information Fields'],
        'show_stu_class' => ['label' => 'Class', 'icon' => 'fa-chalkboard', 'group' => 'Student Information Fields'],
        'show_stu_stream' => ['label' => 'Stream', 'icon' => 'fa-diagram-project', 'group' => 'Student Information Fields'],
        'show_stu_academic_year' => ['label' => 'Academic Year', 'icon' => 'fa-calendar', 'group' => 'Student Information Fields'],
        'show_stu_term' => ['label' => 'Term', 'icon' => 'fa-calendar-days', 'group' => 'Student Information Fields'],
        'show_stu_dob' => ['label' => 'Date of Birth', 'icon' => 'fa-cake-candles', 'group' => 'Student Information Fields'],
        'show_stu_gender' => ['label' => 'Gender', 'icon' => 'fa-venus-mars', 'group' => 'Student Information Fields'],
        'show_stu_class_teacher' => ['label' => 'Class Teacher', 'icon' => 'fa-chalkboard-teacher', 'group' => 'Student Information Fields'],
        'show_stu_house' => ['label' => 'House / Team', 'icon' => 'fa-house', 'group' => 'Student Information Fields'],
        'show_stu_report_date' => ['label' => 'Date of Report', 'icon' => 'fa-clock', 'group' => 'Student Information Fields'],
        'show_stu_status' => ['label' => 'Status', 'icon' => 'fa-flag', 'group' => 'Student Information Fields'],

        // ── Performance Summary strip — per-field toggles ────────────
        'show_sum_total_marks' => ['label' => 'Total Marks', 'icon' => 'fa-clipboard-list', 'group' => 'Summary Bar Fields'],
        'show_sum_average_mark' => ['label' => 'Average Mark', 'icon' => 'fa-chart-column', 'group' => 'Summary Bar Fields'],
        'show_sum_average_pct' => ['label' => 'Average %', 'icon' => 'fa-percent', 'group' => 'Summary Bar Fields'],
        'show_sum_grade' => ['label' => 'Overall Grade', 'icon' => 'fa-award', 'group' => 'Summary Bar Fields'],
        'show_sum_grade_point' => ['label' => 'Grade Point', 'icon' => 'fa-star', 'group' => 'Summary Bar Fields'],
        'show_sum_aggregate' => ['label' => 'Aggregate (PLE-style)', 'icon' => 'fa-calculator', 'group' => 'Summary Bar Fields'],
        'show_sum_division' => ['label' => 'Division', 'icon' => 'fa-trophy', 'group' => 'Summary Bar Fields'],
        'show_sum_position' => ['label' => 'Position / Rank', 'icon' => 'fa-ranking-star', 'group' => 'Summary Bar Fields'],
        'show_sum_subjects' => ['label' => 'No. of Subjects', 'icon' => 'fa-book', 'group' => 'Summary Bar Fields'],
        'show_sum_attendance' => ['label' => 'Attendance', 'icon' => 'fa-calendar-check', 'group' => 'Summary Bar Fields'],

        'show_logo' => ['label' => 'School logo', 'icon' => 'fa-image', 'group' => 'School Header'],
        // ── Modern has two logos (left + right of the school name) that
        // can each be removed independently. Kept as separate keys
        // instead of reusing 'show_logo' so one side can come off while
        // the other stays. Falls back to 'show_logo' if a saved profile
        // predates this split (see the $on() calls in slip-modern).
        'show_logo_left' => ['label' => 'Left school logo', 'icon' => 'fa-image', 'group' => 'School Header'],
        'show_logo_right' => ['label' => 'Right school logo', 'icon' => 'fa-image', 'group' => 'School Header'],
        'show_arabic' => ['label' => 'Arabic school name', 'icon' => 'fa-language', 'group' => 'School Header'],
        'show_motto' => ['label' => 'School motto', 'icon' => 'fa-quote-left', 'group' => 'School Header'],
        'show_contact' => ['label' => 'Phone / email / location', 'icon' => 'fa-phone', 'group' => 'School Header'],

        'show_photo' => ['label' => 'Student photo', 'icon' => 'fa-portrait', 'group' => 'Student Block'],
        'show_minichart' => ['label' => 'Subject mini chart (student vs class)', 'icon' => 'fa-chart-line', 'group' => 'Student Block'],
        'show_qr' => ['label' => 'QR code', 'icon' => 'fa-qrcode', 'group' => 'Student Block'],
        'show_rank' => ['label' => 'Class position / rank', 'icon' => 'fa-trophy', 'group' => 'Student Block'],
        // Whole-block master for just the Name/Gender/Class/Status/LIN/
        // Position text list — independent of the photo/mini-chart/QR
        // toggles above, so it can come off on its own and let those
        // three reflow into the freed space instead of leaving it empty.
        'show_stu_details_block' => ['label' => 'Student details text block (name, class, status, etc.)', 'icon' => 'fa-address-card', 'group' => 'Student Block'],

        'show_total_score' => ['label' => 'Total Score / Marks box', 'icon' => 'fa-hashtag', 'group' => 'Summary Bar'],
        'show_average' => ['label' => 'Average box', 'icon' => 'fa-percent', 'group' => 'Summary Bar'],
        'show_result' => ['label' => 'Result box', 'icon' => 'fa-flag-checkered', 'group' => 'Summary Bar'],

        'show_score_col' => ['label' => 'Score / Marks column', 'icon' => 'fa-list-ol', 'group' => 'Marks Table'],
        'show_dev' => ['label' => 'Development (DEV ↑↓) column', 'icon' => 'fa-arrows-alt-v', 'group' => 'Marks Table'],
        'show_grade_pill' => ['label' => 'Grade pills (A / B / C …)', 'icon' => 'fa-tag', 'group' => 'Marks Table'],
        'show_comment_col' => ['label' => 'Comment column', 'icon' => 'fa-comment-dots', 'group' => 'Marks Table'],
        'show_teacher_col' => ['label' => 'Teacher column', 'icon' => 'fa-chalkboard-teacher', 'group' => 'Marks Table'],
        'show_totals_row' => ['label' => 'Totals / average row', 'icon' => 'fa-sigma', 'group' => 'Marks Table'],

        'show_perf_chart' => ['label' => 'Performance-over-time chart', 'icon' => 'fa-chart-bar', 'group' => 'Bottom Section'],
        'show_remarks' => ['label' => 'Remarks section', 'icon' => 'fa-comment-alt', 'group' => 'Bottom Section'],
        'show_discipline' => ['label' => 'Discipline section', 'icon' => 'fa-user-shield', 'group' => 'Bottom Section'],
        'show_signatures' => ['label' => 'Signature column', 'icon' => 'fa-signature', 'group' => 'Bottom Section'],
        'show_term_dates' => ['label' => 'Term dates', 'icon' => 'fa-calendar-alt', 'group' => 'Bottom Section'],

        'show_footer_timestamp' => ['label' => 'Generation timestamp', 'icon' => 'fa-clock', 'group' => 'Footer'],
        'show_confidential' => ['label' => 'CONFIDENTIAL stamp', 'icon' => 'fa-lock', 'group' => 'Footer'],
        'show_footer_tagline' => ['label' => 'Closing tagline', 'icon' => 'fa-heart', 'group' => 'Footer'],

        // ── Nursery Modern ('nursery-modern') — whole-section masters ──
        // Same "OFF hides the box completely" behaviour as the Primary
        // masters above; the surrounding layout (mid-grid columns, the
        // MY PROFILE / WHO I AM row) reflows to fill the freed space
        // instead of leaving a gap — see preview-kindergarten-2.blade.php.
        'show_section_profile' => ['label' => 'My Profile card (entire section)', 'icon' => 'fa-id-card', 'group' => 'Sections'],
        'show_section_whoiam' => ['label' => 'Who I Am badges (entire section)', 'icon' => 'fa-face-smile', 'group' => 'Sections'],
        'show_section_timeline' => ['label' => 'My Learning Journey (entire section)', 'icon' => 'fa-timeline', 'group' => 'Sections'],
        'show_section_dev_areas' => ['label' => 'Areas of Development (entire section)', 'icon' => 'fa-seedling', 'group' => 'Sections'],
        'show_section_term_fees' => ['label' => 'Term & Fees Information (entire section)', 'icon' => 'fa-coins', 'group' => 'Sections'],
        'show_section_signatures' => ['label' => 'Signature row (entire section)', 'icon' => 'fa-signature', 'group' => 'Sections'],
    ],

    // Colour/accent is intentionally NOT in 'toggles' above — it applies
    // in every scenario of every design template, per your requirement,
    // so the customise page always renders it unconditionally rather
    // than gating it on a capability list.
    'capabilities' => [
        'classic' => [
            'show_border', 'show_watermark',
            'show_logo', 'show_arabic', 'show_motto', 'show_contact',
            'show_photo', 'show_minichart', 'show_qr',
            'show_score_col', 'show_dev', 'show_grade_pill', 'show_comment_col', 'show_teacher_col', 'show_totals_row',
            'show_perf_chart', 'show_remarks', 'show_discipline', 'show_signatures', 'show_term_dates',
            'show_footer_timestamp', 'show_confidential',

            // Whole-section masters
            'show_section_student_info', 'show_section_summary', 'show_section_marks_table',

            // Student Information — per-field
            'show_stu_name', 'show_stu_admission', 'show_stu_class', 'show_stu_stream',
            'show_stu_academic_year', 'show_stu_term', 'show_stu_dob', 'show_stu_gender',
            'show_stu_class_teacher', 'show_stu_house', 'show_stu_report_date', 'show_stu_status',

            // Summary Bar — per-field
            'show_sum_total_marks', 'show_sum_average_mark', 'show_sum_average_pct',
            'show_sum_grade', 'show_sum_grade_point', 'show_sum_aggregate', 'show_sum_division',
            'show_sum_position', 'show_sum_subjects', 'show_sum_attendance',
        ],
        'modern' => [
            'show_border', 'show_watermark',
            'show_logo_left', 'show_logo_right', 'show_arabic', 'show_motto', 'show_contact',
            'show_photo', 'show_minichart', 'show_qr', 'show_rank', 'show_stu_details_block',
            'show_score_col', 'show_dev', 'show_grade_pill', 'show_comment_col', 'show_teacher_col', 'show_totals_row',
            'show_perf_chart', 'show_remarks', 'show_discipline', 'show_signatures', 'show_term_dates',
            'show_footer_timestamp', 'show_confidential',

            // Whole-section masters
            'show_section_student_info', 'show_section_summary', 'show_section_marks_table',

            // Student Information — per-field (Modern's info row only
            // shows this subset; Stream/DOB/etc. aren't part of its
            // design, so those keys are simply left off this list).
            'show_stu_name', 'show_stu_admission', 'show_stu_class', 'show_stu_gender', 'show_stu_status',

            // Summary Bar — per-field (new section for Modern, mirrors
            // Classic's Performance Summary strip using the same keys).
            'show_sum_total_marks', 'show_sum_average_mark', 'show_sum_average_pct',
            'show_sum_grade', 'show_sum_grade_point', 'show_sum_aggregate', 'show_sum_division',
            'show_sum_position', 'show_sum_subjects', 'show_sum_attendance',
        ],
        'minimal' => [
            'show_border', 'show_watermark',
            // Two independent logos either side of the school name, same
            // split as Modern — each can be removed on its own with no
            // placeholder left behind (see $on() fallback to 'show_logo'
            // in slip-minimal for old saved profiles).
            'show_logo_left', 'show_logo_right', 'show_arabic', 'show_motto', 'show_contact',
            'show_photo', 'show_minichart', 'show_qr', 'show_rank', 'show_stu_details_block',
            'show_score_col', 'show_dev', 'show_grade_pill', 'show_comment_col', 'show_teacher_col', 'show_totals_row',
            'show_perf_chart', 'show_remarks', 'show_discipline', 'show_signatures', 'show_term_dates',
            'show_footer_timestamp', 'show_confidential',

            // Whole-section masters
            'show_section_student_info', 'show_section_summary', 'show_section_marks_table',

            // Student Information — per-field (Minimal's ledger only
            // ever showed this subset of fields, mirrors Modern's list).
            'show_stu_name', 'show_stu_admission', 'show_stu_class', 'show_stu_gender', 'show_stu_status',

            // Summary Bar — per-field (new section for Minimal; the CSS
            // already existed but was never actually rendered — mirrors
            // Classic/Modern's exact keys/labels).
            'show_sum_total_marks', 'show_sum_average_mark', 'show_sum_average_pct',
            'show_sum_grade', 'show_sum_grade_point', 'show_sum_aggregate', 'show_sum_division',
            'show_sum_position', 'show_sum_subjects', 'show_sum_attendance',
        ],

        // ── Nursery Design Templates ─────────────────────────────────
        // Mirrors the Primary set above (Classic/Modern/Minimal), but
        // for the "Nursery Design Template" gallery on the pass slips
        // index. Deliberately starts with ONLY the toggles that are
        // known to cut across every design regardless of layout —
        // 'show_border' (decorative border & corners) and
        // 'show_watermark' — same as Accent Colour, which applies
        // unconditionally outside this list entirely.
        //
        // Each nursery-* markup (preview-kindergarten.blade.php /
        // preview-kindergarten-2.blade.php / slip-nursery.blade.php) is
        // still being converted section-by-section from static image
        // panels into dynamic, data-bound HTML/CSS. As each section
        // lands, measure its real $cfg['show_*'] usage the same way the
        // Primary lists above were built, and add the corresponding
        // keys here — do NOT add a key "ahead of time" just because it
        // exists for Primary, or the panel will show switches that
        // silently do nothing for that design, which is exactly the
        // problem this file exists to prevent.
        'nursery-classic' => [
            'show_border', 'show_watermark',
        ],
        'nursery-modern' => [
            'show_border', 'show_watermark',

            // School Header
            'show_logo', 'show_motto',

            // MY PROFILE card — whole-section master + its own fields
            'show_section_profile', 'show_photo',
            'show_stu_name', 'show_stu_class', 'show_stu_stream',

            // WHO I AM badges — whole-section master
            'show_section_whoiam',

            // MY LEARNING JOURNEY — whole-section master
            'show_section_timeline',

            // AREAS OF DEVELOPMENT — whole-section master
            'show_section_dev_areas',

            // TERM & FEES INFORMATION — whole-section master
            'show_section_term_fees',

            // Footer
            'show_section_signatures', 'show_footer_tagline',
        ],
        'nursery-minimal' => [
            'show_border', 'show_watermark',

            // School Header — dual independent logos (each can be
            // removed on its own, same split as Primary Modern/Minimal),
            // motto, and phone/email/location contact line.
            'show_logo_left', 'show_logo_right', 'show_motto', 'show_contact',

            // Student Block — photo, the whole NAME/CLASS/LIN text list
            // (whole-block master), and its individual fields.
            'show_photo', 'show_stu_details_block',
            'show_stu_name', 'show_stu_class', 'show_stu_admission',
        ],
    ],

];