<?php

/*
|--------------------------------------------------------------------------
| Pass Slip Design Templates — Toggle Capability Manifest
|--------------------------------------------------------------------------
|
| Every Design Template (Classic / Modern / Minimal) shares the SAME
| customisation panel today, even though not every toggle actually does
| anything in every template's markup — e.g. "Result box" is currently
| unused by all three, and "Total Score / Marks box" + "Average box"
| only exist in Classic's markup, not Modern's or Minimal's.
|
| This file is the single source of truth fixing that:
|
|   - 'toggles'      => every show_* switch the customise panel CAN
|                        render, with its label/icon/group.
|   - 'capabilities' => for each template key, exactly which of those
|                        switches actually affect its markup. Anything
|                        not listed here is a dead switch for that
|                        design and is hidden from its panel.
|
| The lists below were generated by measuring real usage of $cfg['key']
| inside each slip-*.blade.php file (not just where the key is
| declared). If a template's Blade markup changes to add/remove a
| section, update its list here to match — that's the only place
| this needs to change.
|
*/

return [

    'toggles' => [
        'show_border' => ['label' => 'Decorative border & corners', 'icon' => 'fa-border-all', 'group' => 'Appearance'],
        'show_watermark' => ['label' => 'Watermark (logo / school name)', 'icon' => 'fa-stamp', 'group' => 'Appearance'],

        'show_logo' => ['label' => 'School logo', 'icon' => 'fa-image', 'group' => 'School Header'],
        'show_arabic' => ['label' => 'Arabic school name', 'icon' => 'fa-language', 'group' => 'School Header'],
        'show_motto' => ['label' => 'School motto', 'icon' => 'fa-quote-left', 'group' => 'School Header'],
        'show_contact' => ['label' => 'Phone / email / location', 'icon' => 'fa-phone', 'group' => 'School Header'],

        'show_photo' => ['label' => 'Student photo', 'icon' => 'fa-portrait', 'group' => 'Student Block'],
        'show_minichart' => ['label' => 'Subject mini chart (student vs class)', 'icon' => 'fa-chart-line', 'group' => 'Student Block'],
        'show_qr' => ['label' => 'QR code', 'icon' => 'fa-qrcode', 'group' => 'Student Block'],
        'show_rank' => ['label' => 'Class position / rank', 'icon' => 'fa-trophy', 'group' => 'Student Block'],

        'show_total_score' => ['label' => 'Total Score / Marks box', 'icon' => 'fa-hashtag', 'group' => 'Summary Bar'],
        'show_average' => ['label' => 'Average box', 'icon' => 'fa-percent', 'group' => 'Summary Bar'],
        'show_result' => ['label' => 'Result box', 'icon' => 'fa-flag-checkered', 'group' => 'Summary Bar'],

        'show_score_col' => ['label' => 'Score / Marks column', 'icon' => 'fa-list-ol', 'group' => 'Marks Table'],
        'show_dev' => ['label' => 'Development (DEV ↑↓) column', 'icon' => 'fa-arrows-alt-v', 'group' => 'Marks Table'],
        'show_grade_pill' => ['label' => 'Grade pills (A / B / C …)', 'icon' => 'fa-tag', 'group' => 'Marks Table'],
        'show_comment_col' => ['label' => 'Comment column', 'icon' => 'fa-comment-dots', 'group' => 'Marks Table'],
        'show_teacher_col' => ['label' => 'Teacher column', 'icon' => 'fa-chalkboard-teacher', 'group' => 'Marks Table'],
        'show_totals_row' => ['label' => 'Totals / average row', 'icon' => 'fa-sigma', 'group' => 'Marks Table'],

        'show_perf_chart' => ['label' => 'Performance-over-time chart', 'icon' => 'fa-chart-bar', 'group' => 'Bottom Section'],
        'show_remarks' => ['label' => 'Remarks section', 'icon' => 'fa-comment-alt', 'group' => 'Bottom Section'],
        'show_discipline' => ['label' => 'Discipline section', 'icon' => 'fa-user-shield', 'group' => 'Bottom Section'],
        'show_signatures' => ['label' => 'Signature column', 'icon' => 'fa-signature', 'group' => 'Bottom Section'],

        'show_footer_timestamp' => ['label' => 'Generation timestamp', 'icon' => 'fa-clock', 'group' => 'Footer'],
        'show_confidential' => ['label' => 'CONFIDENTIAL stamp', 'icon' => 'fa-lock', 'group' => 'Footer'],
    ],

    // Colour/accent is intentionally NOT in 'toggles' above — it applies
    // in every scenario of every design template, per your requirement,
    // so the customise page always renders it unconditionally rather
    // than gating it on a capability list.
    'capabilities' => [
        'classic' => [
            'show_border', 'show_watermark',
            'show_logo', 'show_arabic', 'show_motto', 'show_contact',
            'show_photo', 'show_minichart', 'show_qr', 'show_rank',
            'show_total_score', 'show_average',
            'show_score_col', 'show_dev', 'show_grade_pill', 'show_comment_col', 'show_teacher_col', 'show_totals_row',
            'show_perf_chart', 'show_remarks', 'show_discipline', 'show_signatures',
            'show_footer_timestamp', 'show_confidential',
        ],
        'modern' => [
            'show_border', 'show_watermark',
            'show_logo', 'show_arabic', 'show_motto', 'show_contact',
            'show_photo', 'show_minichart', 'show_qr', 'show_rank',
            'show_score_col', 'show_dev', 'show_grade_pill', 'show_comment_col', 'show_teacher_col', 'show_totals_row',
            'show_perf_chart', 'show_remarks', 'show_discipline', 'show_signatures',
            'show_footer_timestamp', 'show_confidential',
        ],
        'minimal' => [
            'show_border', 'show_watermark',
            'show_logo', 'show_arabic', 'show_motto', 'show_contact',
            'show_photo', 'show_minichart', 'show_qr', 'show_rank',
            'show_score_col', 'show_dev', 'show_grade_pill', 'show_comment_col', 'show_teacher_col', 'show_totals_row',
            'show_perf_chart', 'show_remarks', 'show_discipline', 'show_signatures',
            'show_footer_timestamp', 'show_confidential',
        ],
    ],

];